// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import HelpPortal from "./HelpPortal";
const inter = Inter({ subsets: ["latin"] });
import Image from "next/image";
import logo from "../assets/logo.png";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <HelpPortal />
        <div className="flex justify-center items-center bottom-0 left-0 w-full p-4">
          <span className="text-[#440129]">powered by</span>
          <Image src={logo} alt="logo" width={100} height={100} />
        </div>
      </body>
    </html>
  );
}
