import { Inter } from "next/font/google";
import "./globals.css";
import {HelpSharp} from "@mui/icons-material";
import Tooltip from "@mui/material/Tooltip";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Tooltip title="Report issue"
            className={`h-10 w-10 duration-300 fixed right-5 bottom-5 z-50 shadow-lg hover:scale-95 hover:bg-[#440129]  hover:text-white bg-[#440129] text-white  rounded-full `}
          >
            <HelpSharp className="p-2" />
          
        </Tooltip>
      </body>
    </html>
  );
}
